<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Egoist.Voice.csproj" />
    <Reference Include="Egoist.Translation.Contracts">
      <HintPath>..\..\vendor\translation-client\1.0.0\net8.0\Egoist.Translation.Contracts.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Egoist.Translation.Client">
      <HintPath>..\..\vendor\translation-client\1.0.0\net8.0\Egoist.Translation.Client.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
